name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/your-image-name:latest .

    - name: Push Docker image
      run: |
        docker push your-dockerhub-username/your-image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH to AWS EC2 and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Pull the latest Docker image
          docker pull your-dockerhub-username/your-image-name:latest
          
          # Stop and remove the old container if it exists
          docker stop your-container-name || true
          docker rm your-container-name || true
          
          # Run the new Docker container
          docker run -d --name your-container-name -p 80:80 your-dockerhub-username/your-image-name:latest
